# # Pick one or more connectors and list sources.
# web:
#   # Only crawl OWASP domains (subdomains allowed).  See same_domain()
#   allowed_domains:
#     - owasp.org
#     - cheatsheetseries.owasp.org
#   # Start from the 2021 OWASP Top‑10 landing page and each A0X details page.
#   seed_urls:
#     - https://owasp.org/Top10/
#     - https://cheatsheetseries.owasp.org/IndexTopTen.html
#   max_pages: 200
#   rate_limit_seconds: 1
#   # In Colab we ignore robots.txt to allow crawling within a short time.
#   respect_robots_txt: false
#   # Lower the minimum number of words required to save a page; see web.py min_words.
#   min_words: 10
#   # Only the Top10 landing page and Axx_2021-* detail pages:
#   allowed_path_regex: '^(?:/Top10/(?:$|A\d{2}_\d{4}-.*)|/IndexTopTen\.html|/cheatsheets/[^/]+_Cheat_Sheet\.html)$'
#   # Disallow any locale prefix like /Top10/fr/, /Top10/pt-BR/, /Top10/zh-Hant/
#   disallow_path_regex: '^/Top10/[A-Za-z]{2}(?:-[A-Za-z]{2,})?/'
#   # Uncomment to allow a single hop to the OWASP Cheat Sheet Series.
#   # allow_one_hop_to:
#   #   - https://cheatsheetseries.owasp.org/
#   # max_hops: 2

#   # NEW: generic external expansion (no domain allowlist)
#   max_external_hops: 2                # one hop from any seed (A0X pages are seeds)
#   external_require_https: true        # only https externals
#   external_from_sections_regex: 'references'

#   # Optional safety rails (0 disables the cap)
#   external_max_pages_total: 0        # total number of external pages to fetch (set 0 to disable)
#   external_per_domain_cap: 0          # cap per domain (0 = unlimited)

# files:
#   include_globs:
#     - "docs/**/*.md"
#     - "docs/**/*.txt"

# pdf:
#   paths:
#     - "docs/pdfs/*.pdf"

# Pick one or more connectors and list sources.
web:
  allowed_domains:
    - owasp.org
    - cheatsheetseries.owasp.org

  seed_urls:
    - https://owasp.org/Top10/
    - https://cheatsheetseries.owasp.org/IndexTopTen.html

  max_pages: 400
  rate_limit_seconds: 1
  respect_robots_txt: false
  min_words: 10

  # Works whether your matcher checks full URLs or just paths.
  allowed_path_regex: '^(?:/Top10/(?:$|A\d{2}_\d{4}-.*)|/IndexTopTen\.html|/cheatsheets/[^/]+_Cheat_Sheet\.html)$'
  disallow_path_regex: '^/Top10/[A-Za-z]{2}(?:-[A-Za-z]{2,})?/'

  # ✅ Generic external expansion (no curation)
  max_external_hops: 2
  external_require_https: true
  # Follow only links that appear under “reference-like” sections on OWASP pages (structure-based, not domain-based).
  # external_from_sections_regex: '(?i)(references|see also|related|further reading)'
  external_from_sections_regex: 'references'
  # Safety rails to prevent runaway crawls (not a blocklist):
  external_max_pages_total: 120
  external_per_domain_cap: 12

files:
  include_globs:
    - "docs/**/*.md"
    - "docs/**/*.txt"

pdf:
  paths:
    - "docs/pdfs/*.pdf"
