# Pick one or more connectors and list sources.
web:
  # Only crawl OWASP domains (subdomains allowed).  See same_domain()
  allowed_domains:
    - owasp.org
  # Start from the 2021 OWASP Top‑10 landing page and each A0X details page.
  seed_urls:
    - https://owasp.org/Top10/
    # - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
    # - https://owasp.org/Top10/A02_2021-Cryptographic_Failures/
    # - https://owasp.org/Top10/A03_2021-Injection/
    # - https://owasp.org/Top10/A04_2021-Insecure_Design/
    # - https://owasp.org/Top10/A05_2021-Security_Misconfiguration/
    # - https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/
    # - https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/
    # - https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/
    # - https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/
    # - https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_(SSRF)/
  max_pages: 200
  rate_limit_seconds: 1
  # In Colab we ignore robots.txt to allow crawling within a short time.
  respect_robots_txt: false
  # Lower the minimum number of words required to save a page; see web.py min_words.
  min_words: 20
  # Only the Top10 landing page and Axx_2021-* detail pages:
  allowed_path_regex: '^/Top10/(?:$|A\d{2}_\d{4}-)'
  # Disallow any locale prefix like /Top10/fr/, /Top10/pt-BR/, /Top10/zh-Hant/
  disallow_path_regex: '^/Top10/[A-Za-z]{2}(?:-[A-Za-z]{2,})?/'
  # Uncomment to allow a single hop to the OWASP Cheat Sheet Series.
  # allow_one_hop_to:
  #   - https://cheatsheetseries.owasp.org/
  # max_hops: 2

  # NEW: generic external expansion (no domain allowlist)
  max_external_hops: 2                # one hop from any seed (A0X pages are seeds)
  external_require_https: true        # only https externals
  external_from_sections_regex: 'references'

  # Optional safety rails (0 disables the cap)
  external_max_pages_total: 30        # total number of external pages to fetch (set 0 to disable)
  external_per_domain_cap: 0          # cap per domain (0 = unlimited)

files:
  include_globs:
    - "docs/**/*.md"
    - "docs/**/*.txt"

pdf:
  paths:
    - "docs/pdfs/*.pdf"